### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-clearbit-enrichment#1]
**Description**
Access Clearbit Enrichment API 

**Requirements**
- [x] Build methods to access `combined`, `email`, or `company` endpoints.
- [x] Keep under [rate limit of 600 requests/min](https://clearbit.com/docs#rate-limiting)
- [x] Authenticate via API key
- [x] Provide `output` parameter enabling either:
  - [x] `Separate` - The data provided by Clearbit is the sole output
  - [x]  `Append` - The data provided by Clearbit is appended to the original records

**Relevant Links**
https://clearbit.com/docs#enrichment-api

**Possible config**
```
"config":{
  "api":"email"
  "apiKey":"158025712481249"
  "field":"emailAddress",
  "output":"append"
}
```

**Comment by benjamingregory** [comment]
@noahbass Whats the most recent status of this?

**Comment by noahbass** [comment]
2017.01.30 - Methods for combined, email and company endpoints are finished. Currently, I'm working on ensuring the rate limit will not be exceeded. Finally, the output parameter is the last step to complete this issue.

**Comment by noahbass** [comment]
2017.02.01 - Everything on the initial build list has been checked off. Having some problems getting nock to work on my tests, however, the nock setup shouldn't be to different from other setups I've done - so I'm looking into this. Opening a PR asap @benjamingregory.

**Comment by noahbass** [comment]
2017.02.03 - Opened a PR to close this. See #2.

🚀

**Comment by ryw** [comment]
no more work on aries
